
name: Notify On Commit

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Send slack messege
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_ICON: https://github.com/forcedotcom.png?size=48
            SLACK_COLOR: ${{ job.status }}
            SLACK_USERNAME: gh-commit
            SLACK_TITLE: This is a action call
            SLACK_MESSAGE: "testing from github"
