# This is a basic workflow to help you get started with Actions

name: Assign org

on:
 workflow_dispatch:
  inputs:
   branchName:
    description: "Branch Name where assingment should start"
    required: true
    default: "main"
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branchName }}
          
#       - name: install npm
#       - uses: actions/setuo-node@v3
#         with:
#           node-version: 16
#        run: echo "action ran"
